name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.10
      - name: Install tf2pulumi
        uses: pulumi/action-install-tf2pulumi@releases/v1
      - name: Check Out Sources
        uses: actions/checkout@v1

      - run: npm ci
      - run: npm run build
      - run: npm test

      - name: Clone Terraform bridge repository
        run: git clone https://github.com/pulumi/pulumi-terraform-bridge ../pulumi-terraform-bridge
      - name: Test Action on pulumi-vault repository
        uses: ./
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          downstream-name: pulumi-vault
          downstream-url: https://github.com/pulumi/pulumi-vault
          use-provider-dir: true
          pulumi-bot-token: ${{ secrets.PULUMI_BOT_TOKEN }}
          github-actions-token: ${{ secrets.GITHUB_TOKEN }}

