permissions: write-all # Equivalent to default permissions plus id-token: write
name: "Test typescript-action"
on:
  pull_request: null
  push:
    branches:
      - master
      - 'releases/*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
          check-latest: true
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PR_COMMIT_SHA }}
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        with:
          repo: pulumi/pulumictl
          tag: v0.0.31
          cache: enable
      - name: Test Action on Pulumi-AWS
        uses: ./
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          GITHUB_TOKEN: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
          downstream-name: pulumi-aws
          downstream-url: https://github.com/pulumi/pulumi-aws
          use-provider-dir: true
